name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.12.2]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build API
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /t:Build /p:RestoreDuringBuild=false
    - name: Test API
      run: dotnet test --filter FullyQualifiedName~BrainWare.Api.UnitTests --no-build --verbosity normal
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install web app
      run: npm ci
      working-directory: web-app
    - name: Build web app
      run: npm run build --if-present
      working-directory: web-app
    - name: Test web app
      run: npm test
      working-directory: web-app
