name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.12.2]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build API
      run: dotnet build --no-restore
    - name: Test API
      run: dotnet test --no-build --verbosity normal

    - name: Change to web-app directory
      run: cd web-app
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install web app
      run: npm ci
    - name: Build web app
      run: npm run build --if-present
    - name: Test web app
      run: npm test
